---
# playbook
- hosts: localhost
  become: true
  roles:
    - roles/base

- hosts: localhost
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - roles/desktops

#- hosts: localhost
#  become: true
#  roles:
#    - roles/laptops
