---
# playbook
- hosts: all
  become: yes
  roles:
    - roles/base

- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - roles/desktops
#
#- hosts: localhost
#  become: true
#  vars_files:
#  - vars/main.yml
#  roles:
#    - roles/laptops
#
- hosts: all
  become: no
  become_user: zeno
  roles:
    - roles/conditionals/github.yml
    - roles/conditionals/misc.yml
    - tasks/extras/misc/pip.yml