---
# pip packages
- name: "Installing pip packages"
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ pkgs_pip }}"

# required if installing protonvpn
- name: "Installing required pip dep for ProtonVPN"
  ansible.builtin.pip:
    name: "dnspython>=1.16.0"
    extra_args: --user
    #executable: pip3

- name: "Installing pip packages in venv"
  ansible.builtin.pip:
    name: "{{ pip_venv }}"
    virtualenv: /home/{{ lookup('env', 'USER') }}/Documents/venvs/
