---
# tasks file for desktop
#- import_tasks: 00_backup.yml
#  become: false
#
- import_tasks: 01_update.yml
  become: true

- import_tasks: 02_repos.yml
  become: true

- import_tasks: 03_repos_ext.yml
  become: true

- import_tasks: 04_pkgs.yml
  become: true

- import_tasks: 05_pip.yml
  become: false

- import_tasks: 06_github.yml
  become: false

- import_tasks: 07_settings.yml
  become: false

- import_tasks: 08_post.yml
