---
- name: "Enabling the Flathub repo (system-wide)"
  community.general.flatpak_remote:
    name: "flathub"
    state: "present"
    method: "system"
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
