---
# approved
- name: "Checking if Tailscale repo exists"
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/tailscale.repo"
    get_checksum: false
  register: p
  become: false

- name: "Enabling Tailscale repo"
  yum_repository:
    name: "tailscale-stable"
    description: "Tailscale stable"
    baseurl: "https://pkgs.tailscale.com/stable/fedora/$basearch"
    enabled: true
    gpgcheck: true
    gpgkey: "https://pkgs.tailscale.com/stable/fedora/repo.gpg"
  when: p.stat.exists == False
  become: true

- name: "Installing Tailscale"
  ansible.builtin.dnf:
    name: tailscale
    state: latest
    disable_gpg_check: true
  become: true
