- name: "Installing Brave browser required dependencies"
  dnf:
    state: latest
    name:
      - dnf-plugins-core

- name: "Importing Brave security keys and enabling repo"
  yum_repository:
    name: "Brave browser repo"
    description: "Official Brave repo"
    baseurl: "https://brave-browser-rpm-release.s3.brave.com/x86_64/"
    gpgcheck: yes
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    
- name: "Updating cache"
  dnf:
    update_cache: yes

- name: "Installing Brave browser"
  dnf:
    state: latest
    name:
      - brave-browser