- name: "Installing Brave browser required dependencies"
  dnf:
    state: latest
    name:
      - dnf-plugins-core

- name: "Adding Brave browser repo"
  ansible.builtin.command: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/

- name: "Updating cache"
  dnf:
    update_cache: yes

- name: "Installing Brave browser"
  dnf:
    state: latest
    name:
      - brave-browser