# this task should only be run once
- name: "Installing dnf-plugins-core (required)"
  dnf:
    state: latest
    name:
      - dnf-plugins-core

- name: "Adding Docker repo"
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: "Removing old Docker installations"
  dnf:
    state: absent
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine

- name: "Installing Docker"
  dnf:
    state: latest
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: "Starting Docker service"
  ansible.builtin.service:
    name: docker
    state: started