- name: "Executing GitHub tasks if conditions are met"
  ansible.builtin.stat:
    path:
      - /home/{{ lookup('env', 'USER') }}/Documents/from_git/ble.sh
      - /home/{{ lookup('env', 'USER') }}/Documents/from_git/libvibrant
      - /home/{{ lookup('env', 'USER') }}/Documents/from_git/samrewritten
      - /home/{{ lookup('env', 'USER') }}/Documents/from_git/vibrantlinux
      - /home/{{ lookup('env', 'USER') }}/.local/share/Steam/compatibilitytools.d
    get_checksum: no
  register: p

- name: "Reporting if dirs exists"
  ansible.builtin.debug:
    msg: "Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir

- import_tasks:
    - tasks/github/mkdirs.yml
    - tasks/github/git_blesh.yml
    - tasks/github/git_libvibrant.yml
    - tasks/github/git_vibrantlinux.yml
    - tasks/github/git_proton-ge.yml
    - tasks/github/chmod.yml
    - tasks/github/build_blesh.yml
    - tasks/github/build_libvib.yml
    - tasks/github/build_viblin.yml
    - tasks/github/chmod.yml
  when: p.stat.exists == False