- name: "Installing VirtualBox"
  dnf:
    state: latest
    name:
      - "@development-tools"
      - kernel-headers
      - kernel-devel
      - dkms
      - elfutils-libelf-devel
      - qt5-qtx11extras
      - VirtualBox
      - VirtualBox-devel
      - VirtualBox-kmodsrc
      - VirtualBox-server
      - akmod-VirtualBox
      - kmod-VirtualBox
      - python3-VirtualBox