---
repos:
  - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] }} universe"
  - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] }}-updates universe"
  - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] }}-security universe"
  - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] }} multiverse"
  - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] }}-updates multiverse"
  - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] }}-security multiverse"
  - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] }} restricted"
  - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] }}-updates restricted"
  - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] }}-security restricted"
