- name: "Checking if dir exists"
  ansible.builtin.stat:
    path: /home/{{ lookup('env', 'USER') }}/Documents/from_git/samrewritten
    get_checksum: no
  register: p

- name: "Reporting if dir exists"
  ansible.builtin.debug:
    msg: "Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir

- name: "Cloning samrewritten repo"
  ansible.builtin.git:
    repo: 'https://github.com/PaulCombal/SamRewritten.git'
    dest: /home/{{ lookup('env', 'USER') }}/Documents/from_git/samrewritten
  when: p.stat.exists == False

- name: "Installing required packages"
  dnf:
    state: latest
    name:
      - gtkmm30
      - gtkmm30-devel
      - yajl-devel
      - curl-devel
      - g++