- name: "Checking if dir exists"
  ansible.builtin.stat:
    path: /home/{{ lookup('env', 'USER') }}/Documents/from_git/libvibrant
    get_checksum: no
  register: p

- name: "Reporting if dir exists"
  ansible.builtin.debug:
    msg: "Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir

- name: "Cloning ble.sh repo"
  ansible.builtin.git:
    repo: 'https://github.com/akinomyoga/ble.sh.git'
    dest: /home/{{ lookup('env', 'USER') }}/Documents/from_git/ble.sh
  when: p.stat.exists == False

- name: "Building and instaling ble.sh"
  community.general.make:
    chdir: /home/{{ lookup('env', 'USER') }}/Documents/from_git/ble.sh
    target: install
    params: PREFIX=/home/{{ lookup('env', 'USER') }}/.local

- name: "Sourcing ble.sh to .bashrc"
  ansible.builtin.shell: echo 'source ~/.local/share/blesh/ble.sh' >> /home/{{ lookup('env', 'USER') }}/.bashrc
  register: result

- name: "Info"
  ansible.builtin.debug:
    var: result
    msg: "Remember to close and re-open the terminal to let the changes take effect!"