- name: "Checking if dir exists"
  ansible.builtin.stat:
    path: /home/{{ lookup('env', 'USER') }}/Documents/from_git/ble.sh
    get_checksum: no
  register: p

- name: "Reporting if dir exists"
  ansible.builtin.debug:
    msg: "Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir

- name: "Cloning ble.sh repo"
  ansible.builtin.git:
    repo: 'https://github.com/akinomyoga/ble.sh.git'
    dest: /home/{{ lookup('env', 'USER') }}/Documents/from_git/ble.sh
  when: p.stat.exists == False