- name: "Installing ProtonVPN dependencies"
  dnf:
    state: latest
    name:
      - libappindicator-gtk3
      - gnome-shell-extension-appindicator
      - gnome-tweaks

- name: "Downloading ProtonVPN"
  dnf:
    state: present
    name: "https://protonvpn.com/download/protonvpn-stable-release-1.0.1-1.noarch.rpm"
  when: ansible_facts['os_family'] == "RHEL"

- name: "Installing ProtonVPN"
  dnf:
    state: latest
    name: protonvpn