- name: "Adding Sublime repo"
  yum_repository:
    name: sublime-text
    description: Sublime
    baseurl: https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

- name: "Installing Sublime Text"
  dnf:
    state: latest
    name: sublime-text
