---
# pre-tasks for RHEL-based systems
- name: "Update the system"
  import_tasks: roles/base/tasks/rhel.yml
  when: ansible_facts['os_family']|lower == 'redhat'

# pre-tasks for SUSE-based systems
- name: "Update the system"
  import_tasks: roles/base/tasks/suse.yml
  when: ansible_facts['os_family']|lower == 'opensuse'

# pre-tasks for Debian-based systems
- name: "Update the system"
  import_tasks: roles/base/tasks/debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

# pre-tasks for Arch-based systems
- name: "Update the system"
  import_tasks: roles/base/tasks/arch.yml
  when: ansible_facts['os_family']|lower == 'arch'