---
# pre-tasks for RHEL-based systems
- name: "Update the system"
  import_tasks: roles/base/tasks/rhel.yml
  when:
  - ansible_facts['distribution'] == "Fedora"
  - ansible_facts['distribution_major_version'] > "35"

# pre-tasks for SUSE-based systems
- name: "Update the system"
  import_tasks: roles/base/tasks/suse.yml
  when:
  - ansible_facts['distribution'] == "OpenSUSE"

# pre-tasks for Debian-based systems
- name: "Update the system"
  import_tasks: roles/base/tasks/debian.yml
  when:
  - ansible_facts['os_family'] == "Debian"

# pre-tasks for Arch-based systems
- name: "Update the system"
  import_tasks: roles/base/tasks/arch.yml
  when:
  - ansible_facts['os_family'] == "Arch"