---
- hosts: localhost
  become: true
  pre_tasks:
    - name: "Calling system update module"
      include_tasks: /home/zeno/Documents/github/ansible/laptops/modules/module_sys_update.yml

- hosts: localhost
  become: true
  vars_files:
    - /home/zeno/Documents/github/ansible/laptops/repos/key_list.yml
  tasks:
#    - name: "Calling repo module"
#      include_tasks: /home/zeno/Documents/github/ansible/laptops/modules/module_repos.yml
#
#    - name: "Calling utlities module"
#      include_tasks: /home/zeno/Documents/github/ansible/laptops/modules/module_utils.yml
#
#    - name: "Calling GitHub module"
#      include_tasks: /home/zeno/Documents/github/ansible/laptops/modules/module_github.yml
#
#    - name: "Calling lang packs module"
#      include_tasks: /home/zeno/Documents/github/ansible/laptops/modules/module_lang_packs.yml
#
#    - name: "Calling fonts module"
#      include_tasks: /home/zeno/Documents/github/ansible/laptops/modules/module_fonts.yml
#
#    - name: "Calling ProtonVPN module"
#      include_tasks: /home/zeno/Documents/github/ansible/laptops/modules/module_protonvpn.yml
#
    - name: "Calling VisualStudio Code module"
      include_tasks: /home/zeno/Documents/github/ansible/laptops/modules/module_vscode.yml
#
#    - name: "Calling PIP module"
#      include_tasks: /home/zeno/Documents/github/ansible/laptops/modules/module_pip.yml

#    - name: "Calling Flatpak module"
#      include_tasks: /home/zeno/Documents/github/ansible/laptops/modules/module_flatpaks.yml
