---
# site.yml
- name: "Deploy system"
  hosts: "desktop"
  ignore_errors: true
  vars_files:
    - "desktop/vars/main.yml"
    - ".env"

  pre_tasks:
    - name: "Please check if the (remote) username is correct"
      ansible.builtin.pause:
        prompt: |
          Is the (remote) username "{{ ansible_user_id }}" correct?
          If it isn't, please abort.

          -> Press RETURN to continue.
          -> Press Ctrl+c and then "a" to abort.

    - name: "Set up HW acceleration"
      import_tasks: "roles/desktop/tasks/pre_tasks.yml"

  roles:
    - "desktop"
