- name: "Installing vibrantLinux"
  ansible.builtin.shell: ./update.sh
  args:
    chdir: /home/{{ lookup('env', 'USER') }}/Documents/from_git/vibrantlinux

- name: "Echoing path to local-x86_64.conf"
  ansible.builtin.shell: echo "/usr/local/lib64" | sudo tee /etc/ld.so.conf.d/local-x86_64.conf

- name: "Rebuilding"
  ansible.builtin.shell: sudo ldconfig