- name: "Installing libvibrant required repos"
  dnf:
    state: latest
    name:
      - cmake
      - make
      - libX11
      - libX11-devel
      - libXrandr
      - libXrandr-devel.i686
      - libXrandr-devel.x86_64
      - libXNVCtrl
      - libXNVCtrl-devel

- name: "Cloning GitLab repo: libvibrant"
  ansible.builtin.git:
    repo: 'https://gitlab.com/vibrance/libvibrant-legacy.git'
    dest: /home/{{ lookup('env', 'USER') }}/Documents/from_git/libvibrant

- name: "Creating 'build' dir"
  ansible.builtin.file:
    state: directory
    path: /home/{{ lookup('env', 'USER') }}/Documents/from_git/libvibrant/build
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"